name: slcli
adopt-info: slcli
summary: A CLI tool to interact with the SoftLayer API.
description: |
    A command-line interface is also included and can be used to manage various SoftLayer products and services.
    SLCLI documentation can be found here: https://softlayer-python.readthedocs.io/en/latest/

license: MIT
website: https://www.ibm.com/cloud
source-code: https://github.com/softlayer/softlayer-python
issues: https://github.com/softlayer/softlayer-python/issues
contact: https://github.com/softlayer/softlayer-python
icon: snap/local/slcli.png
base: core24
grade: stable 
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]

apps:
  slcli:
    command: bin/slcli
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - network-bind
     
parts: 
  slcli:
    source: https://github.com/softlayer/softlayer-python
    source-type: git
    plugin: python      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//')"
    
    build-packages:
      - python3
      
    stage-packages:
      - python3   
